### PR TITLE
Install Libtool in build script

### LINKED ISSUE #40: Can't exec "libtoolize": No such file or directory at
With the addition of the read smart contract functionality just merged on the `poa-explorer` repo, we are running into issues on the deploy script.

I had a similar error on my local machine. I'll try and add libtool to the build script.

```
[stdout]Can't exec "libtoolize": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 345, <GEN3> line 5.
[stdout]autoreconf: failed to run libtoolize: No such file or directory
[stdout]autoreconf: libtoolize is needed because this package uses Libtool
[stdout]===> Hook for compile failed!
[stdout]
[stderr]** (Mix) Could not compile dependency :libsecp256k1, "/home/ec2-user/.mix/rebar3 bare compile --paths "/opt/app/_build/prod/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile libsecp256k1", update it with "mix deps.update libsecp256k1" or clean it with "mix deps.clean libsecp256k1"
```

### PR DESCRIPTION
**Pull request by acravenho**
Fixes #40

With the merge of the read contract functionality `libtoolize` was needed  for one of the dependencies. After testing the fix, I was able to successfully complete the deployment.

Here is the temporary build with this fix: http://sokab-explorer-sokol-elb-1771258833.us-east-1.elb.amazonaws.com/en

### CODE REVIEW

File: modules/stack/libexec/init.sh [hunk 1]
```diff
@@ -59,6 +59,10 @@ if ! which git >/dev/null; then
     log "Installing git.."
     yum install -y --enablerepo=epel git >"$LOG"
 fi
+if ! which libtool >/dev/null; then
+    log "Installing libtool.."
+    yum install -y libtool >"$LOG"
```
Comment (KronicDeth) [inline modules/stack/libexec/init.sh]: Did you check if we should be getting `libtool` from the `epel` repo using `--enablerepo=epel`?  If it is available in `epel`, we should use the epel version.
